command /adamob:
	trigger:
		if {asb::%player%.mob} is not set:
			if player is in asb world:
				if asb owner of island at (location of player) is player:
					set {asb::%player%.mob} to now
					send "&6Ada MOB &f» &aArtık adanda mob doğmuyor."
				else:
					send "&6Ada MOB &f» &cBunu ancak ada sahibi yapabilir."
			else:
				send "&6Ada MOB &f» &cAdada olman gerek."
		else:
			delete {asb::%player%.mob}
			send "&6Ada MOB &f» &aArtık adanda mob doğuyor."
on spawn:
	event-entity is in asb world
	{asb::%asb owner of island at event-entity%.mob} is set
	delete event-entity
on asb new:
	delete {asb::%player%.mob}
on asb reset:
	delete {asb::%player%.mob}
