options:
	prefix: &b&lEien&3&lMC &f&l»
	sharpness-tr: Keskinlik
	baneofarthropods-tr: Eklembacaklıların Kıyameti
	unbreaking-tr: Kırılmazlık
	projectileprotection-tr: Hasar Koruması
	protection-tr: Koruma
	smite-tr: Darbe
	featherfalling-tr: Tüyüş Düşüşü
	fireprotection-tr: Ateş Koruması
	aquaaffinity-tr: Su Adaptasyonu
	respiration-tr: Solungaç
	flame-tr: Alev
	punch-tr: Yumruk
	power-tr: Güç
	efficiency-tr: Verimlilik
	looting-tr: Ganimet
	fireaspect-tr: Alevden Çehre
	knockback-tr: Savurma
	fortune-tr: Servet
	infinity-tr: Sonsuzluk
	silktouch-tr: İpeksi Dokunuş
	blastprotection-tr: Patlama Koruması
	
	#büyü ayarlamalar
	sharpness: 100
	baneofarthropods: 50
	unbreaking: 100
	projectileprotection: 150
	protection: 150
	smite: 100
	featherfalling: 100
	aquaaffinity: 50
	respiration: 50
	flame: 125
	punch: 125
	power: 125
	efficiency: 150
	looting: 100
	fireaspect: 150
	knockback: 175
	fortune: 150
	infinity: 750
	silktouch: 250
	fireprotection: 150
	blastprotection: 100
function enchMarket(p: player):
	open virtual chest with size 5 named "&1EnchMarket" to {_p}
	make gui slot 0 of {_p} with diamond sword named "&7Kılıç" to run function sword({_p})
	make gui slot 4 of {_p} with diamond pickaxe named "&7Kazma Kürek Balta" to run function kkb({_p})
	make gui slot 8 of {_p} with bow named "&7Yay" to run function yay({_p})
	make gui slot 44 of {_p} with barrier named "&cÇıkış" to close
	if {_p} does not have permission "lord.enchmarket":
		make gui slot 13 of {_p} with diamond helmet named "&7Kask" with lore "||&cBunu kullanmak için &bEienLord &colman gerek.||" to nothing
		make gui slot 22 of {_p} with diamond chestplates named "&7Zırh" with lore "||&cBunu kullanmak için &bEienLord &colman gerek.||" to nothing
		make gui slot 31 of {_p} with diamond leggings named "&7Pantalon" with lore "||&cBunu kullanmak için &bEienLord &colman gerek.||" to nothing
		make gui slot 40 of {_p} with diamond boots named "&7Bot" with lore "||&cBunu kullanmak için &bEienLord &colman gerek.||" to nothing
		stop
	make gui slot 13 of {_p} with diamond helmet named "&7Kask" to run function xhelmet({_p})
	make gui slot 22 of {_p} with diamond chestplates named "&7Zırh" to run function xchestplates({_p})
	make gui slot 31 of {_p} with diamond leggings named "&7Pantalon" to run function xleggings({_p})
	make gui slot 40 of {_p} with diamond boots named "&7Bot" to run function xboots({_p})
function sword(p: player):
	open virtual chest with size 2 named "&7Kılıç büyüleri" to {_p}
	make gui slot 0 of {_p} with enchanted book named "&a{@sharpness-tr}" with lore "&e{@sharpness} XP||||&fEkstra hasas verir.||||" to run function buyu({_p}, diamond sword, sharpness)
	make gui slot 2 of {_p} with enchanted book named "&a{@smite-tr}" with lore "&e{@smite} XP||||&fVurulan varlığa ekstra hasas verir.||||" to run function buyu({_p}, diamond sword, smite)
	make gui slot 4 of {_p} with enchanted book named "&a{@baneofarthropods-tr}" with lore "&e{@baneofarthropods} XP||||&fMoblara ekstra hasas verir.||||" to run function buyu({_p}, diamond sword, bane of arthropods)
	make gui slot 6 of {_p} with enchanted book named "&a{@knockback-tr}" with lore "&e{@knockback} XP||||&fVurulan varlığın geriye savrulmasını sağlar.||||" to run function buyu({_p}, diamond sword, knockback)
	make gui slot 8 of {_p} with enchanted book named "&a{@fireaspect-tr}" with lore "&e{@fireaspect} XP||||&fVurulan varlığın yanmasını sağlar.||||" to run function buyu({_p}, diamond sword, fire aspect)
	make gui slot 10 of {_p} with enchanted book named "&a{@looting-tr}" with lore "&e{@looting} XP||||&fMobların daha fazla eşya düşürmesini sağlar.||||" to run function buyu({_p}, diamond sword, looting)
	make gui slot 12 of {_p} with enchanted book named "&a{@unbreaking-tr}" with lore "&e{@unbreaking} XP||&fAletin her kullanımında dayanımının||&fazalmama ihtimali olur.||||" to run function buyu({_p}, diamond sword, unbreaking)
	make gui slot 17 of {_p} with barrier named "&cGeri dön." to run function enchMarket({_p})
function kkb(p: player):
	open virtual chest with size 1 named "&7Kazma/Kürek/Balta büyüleri" to {_p}
	make gui slot 0 of {_p} with enchanted book named "&a{@efficiency-tr}" with lore "&e{@efficiency} XP||||&fAletin daha hızlı kazmasını sağlar.||||" to run function buyu({_p}, diamond pickaxe, efficiency)
	make gui slot 2 of {_p} with enchanted book named "&a{@silktouch-tr}" with lore "&e{@silktouch} XP||||&fKırılacak bloğun orjinal haliyle düşmesini sağlar.||||" to run function buyu({_p}, diamond pickaxe, silk touch)
	make gui slot 4 of {_p} with enchanted book named "&a{@fortune-tr}" with lore "&e{@fortune} XP||||&fBloktan düşebilecek kaynak sayısını arttırır.||||" to run function buyu({_p}, diamond pickaxe, fortune)
	make gui slot 6 of {_p} with enchanted book named "&a{@unbreaking-tr}" with lore "&e{@unbreaking} XP||||&fAletin her kullanımında dayanımının azalmama ihtimali olur.||||" to run function buyu({_p}, diamond pickaxe, unbreaking)
	make gui slot 8 of {_p} with barrier named "&cGeri dön." to run function enchMarket({_p})
function yay(p: player):
	open virtual chest with size 2 named "&7Yay büyüleri" to {_p}
	make gui slot 0 of {_p} with enchanted book named "&a{@power-tr}" with lore "&e{@power} XP||||&fEkstra hassas verir.||||" to run function buyu({_p}, bow, power)
	make gui slot 2 of {_p} with enchanted book named "&a{@punch-tr}" with lore "&e{@punch} XP||||&fVurulan varlığın geri savrulmasını sağlar.||||" to run function buyu({_p}, bow, punch)
	make gui slot 4 of {_p} with enchanted book named "&a{@flame-tr}" with lore "&e{@flame} XP||||&fVurulan varlığın yanmasını sağlar.||||" to run function buyu({_p}, bow, flame)
	make gui slot 6 of {_p} with enchanted book named "&a{@infinity-tr}" with lore "&e{@infinity} XP||||&fVurulan varlığın yanmasını sağlar.||||" to run function buyu({_p}, bow, infinity)
	make gui slot 8 of {_p} with enchanted book named "&a{@unbreaking-tr}" with lore "&e{@unbreaking} XP||||&fAletin her kullanımında dayanımının azalmama ihtimali olur.||||" to run function buyu({_p}, bow, unbreaking)
	make gui slot 17 of {_p} with barrier named "&cGeri dön." to run function enchMarket({_p})
function xhelmet(p: player):
	open virtual chest with size 2 named "&7Kask büyüleri" to {_p}
	make gui slot 0 of {_p} with enchanted book named "&a{@protection-tr}" with lore "&e{@protection} XP||||&fÇevresel hasarlardan koruma sağlar.||||" to run function buyu({_p}, diamond helmet, protection)
	make gui slot 2 of {_p} with enchanted book named "&a{@fireprotection-tr}" with lore "&e{@fireprotection} XP||||&fAteşe karşı koruma sağlar.||||" to run function buyu({_p}, diamond helmet, fire protection)
	make gui slot 4 of {_p} with enchanted book named "&a{@blastprotection-tr}" with lore "&e{@blastprotection} XP||||&fPatlamalarına karşı koruma sağlar.||||" to run function buyu({_p}, diamond helmet, blast protection)
	make gui slot 6 of {_p} with enchanted book named "&a{@projectileprotection-tr}" with lore "&e{@projectileprotection} XP||||&fOk ve benzerlerine karşı koruma sağlar.||||" to run function buyu({_p}, diamond helmet, projectile protection)
	make gui slot 8 of {_p} with enchanted book named "&a{@respiration-tr}" with lore "&e{@respiration} XP||||&fSuda daha uzun süre nefessiz kalmayı||&fayrıca boğulurken sağlığın daha yavaş||&fazalmasını sağlar.||||" to run function buyu({_p}, diamond helmet, aqua affinity)
	make gui slot 10 of {_p} with enchanted book named "&a{@aquaaffinity-tr}" with lore "&e{@aquaaffinity} XP||||&fSu altında blok kırabilme||&fhızını artırır.||||" to run function buyu({_p}, diamond helmet, aqua affinity)
	make gui slot 17 of {_p} with barrier named "&cGeri dön." to run function enchMarket({_p})
function xchestplates(p: player):
	open virtual chest with size 1 named "&7Zırh büyüleri" to {_p}
	#chestplates
	chestleg({_p}, diamond chestplates)
	make gui slot 8 of {_p} with barrier named "&cGeri dön." to run function enchMarket({_p})
function xleggings(p: player):
	open virtual chest with size 1 named "&7Pantalon büyüleri" to {_p}
	chestleg({_p}, diamond leggings)
	make gui slot 8 of {_p} with barrier named "&cGeri dön." to run function enchMarket({_p})
	#chestplates
function xboots(p: player):
	open virtual chest with size 2 named "&7Bot büyüleri" to {_p}
	# chestplates
	chestleg({_p}, diamond boots)
	make gui slot 8 of {_p} with enchanted book named "&a{@featherfalling-tr}" with lore "&e{@featherfalling} XP||||&fDüşüşlerde alınan hasarı azaltır.||||" to run function buyu({_p}, diamond boots, feather falling)
	make gui slot 17 of {_p} with barrier named "&cGeri dön." to run function enchMarket({_p})
function chestleg(p: player, item: material):
	make gui slot 0 of {_p} with enchanted book named "&a{@protection-tr}" with lore "&e{@protection} XP||||&fÇevresel hasarlardan koruma sağlar.||||" to run function buyu({_p}, {_item}, protection)
	make gui slot 2 of {_p} with enchanted book named "&a{@fireprotection-tr}" with lore "&e{@fireprotection} XP||||&fAteşe karşı koruma sağlar.||||" to run function buyu({_p}, {_item}, fire protection)
	make gui slot 4 of {_p} with enchanted book named "&a{@blastprotection-tr}" with lore "&e{@blastprotection} XP||||&fPatlamalarına karşı koruma sağlar.||||" to run function buyu({_p}, {_item}, blast protection)
	make gui slot 6 of {_p} with enchanted book named "&a{@projectileprotection-tr}" with lore "&e{@projectileprotection} XP||||&fOk ve benzerlerine karşı koruma sağlar.||||" to run function buyu({_p}, {_item}, projectile protection)
function hesap(p: player, xp: integer, b: enchantment, t: text):
	set {_ench} to enchant level of {_b} of {_p}'s tool
	set {_xp} to ({_ench} + 1) * {_xp}
	if {_p}'s level is bigger than or equal to {_xp}:
		remove {_xp} from {_p}'s level
		enchant {_p}'s tool with "%{_b}% %{_ench} + 1%" parsed as enchantment type
		send "{@prefix} &aHesabından %{_xp}% XP çekildi." to {_p}
		send "{@prefix} &aBaşarıyla %{_t}% %{_ench} + 1% level büyü basıldı." to {_p}
		stop
	else:
		send "{@prefix} &cYeteri kadar XP'in yok. Gereken XP: &d%{_xp} - {_p}'s level%" to {_p}
function ozelhesap(p: player, xp: integer, b: enchantment, t: text):
	if enchant level of {_b} of {_p}'s tool is bigger than or equal to 1:
		send "{@prefix} &cEn fazla 1 büyü level basabilirsin." to {_p}
		stop
	else:
		if {_p}'s level is bigger than or equal to {_xp}:
			remove {_xp} from {_p}'s level
			enchant {_p}'s tool with "%{_b}% 1" parsed as enchantment type
			send "{@prefix} &aHesabından %{_xp}% XP çekildi." to {_p}
			send "{@prefix} &aBaşarıyla %{_t}% 1 level büyü basıldı." to {_p}
		else:
			send "{@prefix} &cYeteri kadar XP'in yok. Gereken XP: &d%{_xp} - {_p}'s level%" to {_p}
function buyu(p: player, i: item, b: enchantment):
	{_p}'s tool is not diamond pickaxe named "&a&lSpawner Kazması"
	item amount of type of tool of {_p} <= 1
	if "%type of tool of {_p}%" is "%{_i}%":
		if {_b} is unbreaking:
			set {_y} to "{@unbreaking-tr}"
			hesap({_p}, {@unbreaking}, {_b}, {_y})
		if {_b} is protection:
			set {_y} to "{@protection-tr}"
			hesap({_p}, {@protection}, {_b}, {_y})
		if {_b} is projectile protection:
			set {_y} to "{@projectileprotection-tr}"
			hesap({_p}, {@projectileprotection}, {_b}, {_y})
		if {_b} is sharpness:
			set {_y} to "{@sharpness-tr}"
			hesap({_p}, {@sharpness}, {_b}, {_y})
		if {_b} is smite:
			set {_y} to "{@smite-tr}"
			hesap({_p}, {@smite}, {_b}, {_y})
		if {_b} is knockback:
			set {_y} to "{@knockback-tr}"
			hesap({_p}, {@knockback}, {_b}, {_y})
		if {_b} is bane of arthropods:
			set {_y} to "{@baneofarthropods-tr}"
			hesap({_p}, {@baneofarthropods}, {_b}, {_y})
		if {_b} is fire aspect:
			set {_y} to "{@fireaspect-tr}"
			hesap({_p}, {@fireaspect}, {_b}, {_y})
		if {_b} is looting:
			set {_y} to "{@looting-tr}"
			hesap({_p}, {@looting}, {_b}, {_y})
		if {_b} is efficiency:
			set {_y} to "{@efficiency-tr}"
			hesap({_p}, {@efficiency}, {_b}, {_y})
		if {_b} is silk touch:
			set {_y} to "{@silktouch-tr}"
			ozelhesap({_p}, {@silktouch}, {_b}, {_y})
		if {_b} is fortune:
			set {_y} to "{@fortune-tr}"
			hesap({_p}, {@fortune}, {_b}, {_y})
		if {_b} is punch:
			set {_y} to "{@punch-tr}"
			hesap({_p}, {@punch}, {_b}, {_y})
		if {_b} is flame:
			set {_y} to "{@flame-tr}"
			hesap({_p}, {@flame}, {_b}, {_y})
		if "%{_b}%" is "infinity":
			set {_y} to "{@infinity-tr}"
			ozelhesap({_p}, {@infinity}, {_b}, {_y})
		if "%{_b}%" is "power":
			set {_y} to "{@power-tr}"
			hesap({_p}, {@power}, {_b}, {_y})
		if {_b} is feather falling:
			set {_y} to "{@featherfalling-tr}"
			hesap({_p}, {@featherfalling}, {_b}, {_y})
		if {_b} is respiration:
			set {_y} to "{@respiration-tr}"
			hesap({_p}, {@respiration}, {_b}, {_y})
		if {_b} is aqua affinity:
			set {_y} to "{@aquaaffinity-tr}"
			hesap({_p}, {@aquaaffinity}, {_b}, {_y})
		if {_b} is fire protection:
			set {_y} to "{@fireprotection-tr}"
			hesap({_p}, {@fireprotection}, {_b}, {_y})
		if {_b} is blast protection:
			set {_y} to "{@blastprotection-tr}"
			hesap({_p}, {@blastprotection}, {_b}, {_y})
	else:
		send "{@prefix} &cİlk önce eline &b%{_i}% &calmalısın!" to {_p}
on right click on enchantment tables:
	cancel event
	enchMarket(player)
command /enchmarket:
	trigger:
		enchMarket(player)
