options:
	tabela: "[fautosell]" or "[fas]"
	line1: &6&m-------
	line2: &7&lFAuto&8&lSell&b&lSK # Sakın boş bırakma
	line3: %player% #Bu şekilde bırakmak zorundasınız.
	saniye: 3
	prefix: &7&lFAuto&8&lSell&b&lSK &f&l»
	kirildi: &aTabela başarıyla kırıldı.
	sandiksenindegil: &cSandık senin değil, kıramazsın!
	menüisim: &e&l[ &6&lSandıklarım &e&l]
	başarıylaışınlandın: &aBaşarıyla sandığa ışınlandın.
	sandığınbulunamadı: &cSandık bulunamadı.
	hunikoyamazsın: &c&nSadece sandığın altına&c huni koyulamaz.
	sandığabak: &cTabelaya bak.
	yanlışsandık: &cBaktığın tabela, FAutoSell tabelası değil.
	isimyaz: &cHatalı kullanım: &e/fas değiştir &4[<isim>]
	hak: false
	haksayisi: 3 #Aktif etmek için hak kısmı true diye ayarlı olmalı.
	hakkındoldu: &cHakkın kalmadı.
on sign change:
	line 1 is {@tabela}
	block behind event-block is chest
	if {@hak} is true:
		set {_hak::*} to skutil yaml list "fautosellsk.%player%" from file "plugins/FAutoSellSK/data.yml"
		if size of {_hak::*} >= {@haksayisi}:
			send "{@prefix} {@hakkındoldu}"
			cancel event
			stop
	add location of block behind event-block to skutil yaml list "fautosellsk.%player%" from file "plugins/FAutoSellSK/data.yml"
	set line 1 to "{@line1}"
	set line 2 to "{@line2}"
	set line 3 to "{@line3}"
	set line 4 to "{@saniye}"
on break:
	event-block is sign
	line 2 is "{@line2}"
	if player is not op:
		line 3 is not player
		send "{@prefix} {@sandiksenindegil}"
		cancel event
		stop
	remove location of block behind event-block from skutil yaml list "fautosellsk.%line 3 of event-block%" from file "plugins/FAutoSellSK/data.yml"
	send "{@prefix} {@kirildi}"
on place:
	event-block is hopper
	block 1 above event-block is chest
	loop all blocks in radius 1 around block 1 above event-block:
		loop-block is wall sign
		line 2 of loop-block is "{@line2}"
		send "{@prefix} {@hunikoyamazsın}"
		cancel event
		stop loop
on load:
	if yaml "fautosellsk" in file "plugins\FAutoSellSK\data.yml" does not exist:
		create file "plugins\FAutoSellSK\data.yml"
	if yaml "ayarlar" in file "plugins\FAutoSellSK\ayarlar.yml" does not exist:
		create file "plugins\FAutoSellSK\ayarlar.yml"
		set skutil yaml value "ayarlar.stone" from file "plugins\FAutoSellSK\ayarlar.yml" to 1
every 1 seconds:
	loop all players:
		if skutil yaml list "fautosellsk.%loop-player%" from file "plugins/FAutoSellSK/data.yml" is set:
			set {_set::*} to skutil yaml list "fautosellsk.%loop-player%" from file "plugins/FAutoSellSK/data.yml"
			loop {_set::*}:
				if "%block at loop-value-2%" is not "chest":
					remove loop-value-2 from skutil yaml list "fautosellsk.%loop-player%" from file "plugins/FAutoSellSK/data.yml"
					stop
				tabela(loop-player, loop-value-2)
			stop
		add location of loop-player to yaml list "fautosellsk.%loop-player%" from file "plugins/FAutoSellSK/data.yml"
function tabela(p : player, b : location):
	loop all items in inventory of block at {_b}:
		loop {list::*}:
			"%loop-value-2%" is "%type of loop-item%"
			set {_item} to type of loop-item
	{_item} is set
	set {_int} to line 4 of block in front of block at {_b}
	({_int} parsed as integer) > 0:
		set line 4 of block in front of block at {_b} to "%({_int} parsed as integer) - 1%"
		stop
	set line 4 of block in front of block at {_b} to "{@saniye}"
	sat({_p}, {_item}, {_b})
function sat(p : player, m: material, b: location):
	set {_adet} to number of {_m} in inventory of block at {_b}
	set {_fiyat} to skutil yaml value "ayarlar.%{_m}%" from file "plugins\FAutoSellSK\ayarlar.yml"
	add {_adet} * {_fiyat} to {_p}'s balance
	remove all {_m} from inventory of block at {_b}
command /fas [<text>] [<text>]:
	permission: fas.reload
	permission: &cBunu yapmak için yetkin yok. &f(&4permission: fas.reload&f)
	trigger:
		if arg-1 is "reload":
			delete {list::*}
			set {list::*} to skutil yaml nodes "ayarlar" from file "plugins\FAutoSellSK\ayarlar.yml"
			send "{@prefix} &aayarlar.yml adlı metin yenilendi."
			stop trigger
		if arg-1 is "değiştir":
			if targeted block is wall sign or sign:
				if line 2 of targeted block is "{@line2}":
					if arg-2 is set:
						set line 3 of targeted block to arg-2
						stop trigger
					send "{@prefix} {@isimyaz}"
					stop trigger
				send "{@prefix} {@yanlışsandık}"
				stop trigger
			send "{@prefix} {@sandığabak}"
			stop trigger
		send "{@prefix} &cHatalı kullanım"
		send "&3» &b/fas reload"
		send "&3» &b/fas değiştir <oyuncu>"
command /sandıklarım:
	trigger:
		if skutil yaml list "fautosellsk.%player%" from file "plugins/FAutoSellSK/data.yml" is set:
			set {_set::*} to skutil yaml list "fautosellsk.%player%" from file "plugins\FAutoSellSK\data.yml"
			open virtual chest with size 1 named "{@menüisim}" to player
			set {_n} to 1
			loop {_set::*}:
				make gui slot ({_n} - 1) of player with chest named "&7##%{_n}%. &6Sandığın burda! &cIşınlamak için tıkla!" to run function isinla(player, loop-value)
				add 1 to {_n}
			stop trigger
		send "{@prefix} {@sandığınbulunamadı}"
function isinla(p: player, l: location):
	teleport {_p} to {_l}
	send "{@prefix} {@başarıylaışınlandın}" to {_p}
