import:
    org.bukkit.event.player.PlayerFishEvent
    org.bukkit.inventory.ItemStack
on PlayerFishEvent:
	send "%event.getState()%" to event.getPlayer()
	if "%event.getState()%" = "BITE":
		send "&aHadi yakala!" to event.getPlayer()
	if "%event.getState()%" = "CAUGHT_FISH":
		send "&bYakaladın!" to event.getPlayer()
		#set {_item} to random element out of {fishing::items::*}
		#set {_itemtype} to {_item}.getType()
		#set {_itemamount} to {_item}.getAmount()
		event.getCaught().getItemStack().setItemStack(random element out of {fishing::items::*})
		#event.getCaught().getItemStack().setType({_itemtype})
command /adminfish:
	permission: op
	permission message: &cAdminler kullanabilir.
	trigger:
		open AdminFishGUI(player) to player
		stop trigger
function AdminFishGUI(p : player) :: inventory:
	set metadata tag "AdminFishGUI" of {_p} to chest inventory with 6 rows named "&0Admin&8Fish&7GUI"
	loop {fishing::items::*}:
		set slot {_x} + 0 of (metadata tag "AdminFishGUI" of {_p}) to loop-value
		add 1 to {_x}
	return (metadata tag "AdminFishGUI" of {_p})
on inventory close:
	name of event-inventory = "&0Admin&8Fish&7GUI"
	loop items in event-inventory:
		loop-item is not air
		add loop-item to {_relfishing::items::*}
	set {fishing::items::*} to {_relfishing::items::*}
	if {_relfishing::items::*} is not set:
		delete {fishing::items::*} 
	send "&aGüncellendi."