#Version 0.1 by bnjrKemal
options:

	# Buraya gruplarını ekleyebilirsiniz.(Sırayla)
	birincigrup: Acemi
	ikincigrup: Çaylak
	üçüncügrup: Tecrübeli
	dördüncügrup: Kahraman
	# --------------------------------------------

	mesaj: &e%{_p}% &badlı oyuncu, &e%{_verilecekgrup}%&b rütbesine yükseldi.
	yetersizpara: &cYeteri kadar paran yok.
	prefix: &e&l• &6&lFRütbe &f&l»
	rütbenyok: &cHer hangi bir rütbeye sahip değilsin.
	sonrütbe: &cSon rütbedesin, dostum.

command /rütbe:
	trigger:
		if player's group is "{@birincigrup}":
			atla(player, "{@birincigrup}", "{@ikincigrup}", 100000) # (player, cikarilacakgrup, verilecekgrup, para) bu şekilde
			stop trigger # bu önemlidir.
		if player's group is "{@ikincigrup}":
			atla(player, "{@ikincigrup}", "{@üçüncügrup}", 200000)
			stop trigger
		if player's group is "{@üçüncügrup}":
			atla(player, "{@üçüncügrup}", "{@dördüncügrup}", 300000)
			stop trigger
		if player's group is "{@dördüncügrup}":
			send "{@prefix} {@sonrütbe}"
			stop trigger
		else:
			send "{@prefix} {@rütbenyok}"
		# Burdan devam edebilirsiniz..

function atla(p : player, cikarilacakgrup: text, verilecekgrup: text, i : integer):
	if {_p}'s balance is bigger than or equal to {_i}:
		remove {_i} from {_p}'s balance
		remove "%{_cikarilacakgrup}%" from {_p}'s group
		add "%{_verilecekgrup}%" to {_p}'s group
		send "{@prefix} {@mesaj}" to players
	else:
		send "{@prefix} {@yetersizpara}" to {_p}
