on command:
	log "%sender% -> %full command%" to "komut\global.yml"
on chat:
	log "%player% -> %message%" to "sohbet\oyuncu\%player%.yml"
	log "%player% -> %message%" to "sohbet\global.yml"
on drop:
	log "%player% -> %event-item% isim: %name of event-item%" to "drop\global.yml"
on pickup:
	log "%player% -> %event-item% isim: %name of event-item%" to "pickup\%now%.yml"
	log "%player% -> %event-item% isim: %name of event-item%" to "pickup\global.yml"
on break:
	if player is not in "ASkyBlock":
		if "%region at player%" does not contain "obsidyenss":
			log "%player% -> %location of targeted block%" to "break\%player's world%.yml"
