command /market:
	trigger:
		send "&6&lSanal Market &f&l» &aHızlı satmak için &c/sell all" 
		market(player)
function market(p: player):
	open virtual chest with 6 row named "&b&lMarket" to {_p}
	add skutil yaml nodes "listeler" from file "plugins/SanalMarket/market.yml" to {_list::*}
	loop {_list::*}:
		set {_item} to skutil yaml value "listeler.%loop-value%.item" from file "plugins/SanalMarket/market.yml"
		set {_name} to skutil yaml value "listeler.%loop-value%.name" from file "plugins/SanalMarket/market.yml"
		set {_slot} to skutil yaml value "listeler.%loop-value%.slot" from file "plugins/SanalMarket/market.yml"
		make gui slot {_slot} - 1 of {_p} with ({_item} parsed as material) named "%{_name}%" to run function iceri({_p}, "%loop-value%", "%{_name}%")
function iceri(p: player, kategori: text, name: text):
	add skutil yaml nodes "ayarlar.%{_kategori}%" from file "plugins/SanalMarket/ayarlar.yml" to {_ayarlar::*}
	open virtual chest with 6 row named "%{_name}%" to {_p}
	loop {_ayarlar::*}:
		set {_alis} to skutil yaml value "ayarlar.%{_kategori}%.%loop-value%.alis" from file "plugins/SanalMarket/ayarlar.yml"
		set {_satis} to skutil yaml value "ayarlar.%{_kategori}%.%loop-value%.satis" from file "plugins/SanalMarket/ayarlar.yml"
		set {_slot} to skutil yaml value "ayarlar.%{_kategori}%.%loop-value%.slot" from file "plugins/SanalMarket/ayarlar.yml"
		make gui slot {_slot} - 1 of {_p} with (loop-value parsed as material) with lore "&a&lAlış: %{_alis}%||&c&lSatış: %{_satis}%" to run function onaymarket({_p}, "%loop-value%", "%{_alis}%", "%{_satis}%", "&a&lAlış: %{_alis}%||&c&lSatış: %{_satis}%")
	make gui slot (size of {_ayarlar::*}) of {_p} with barrier named "&cGeri git" to run function market({_p})
function onaymarket(p: player, item: text, alis: text, satis: text, bilgi: text):
	open virtual chest with 6 row named "Al Sat" to {_p}
	make gui slot 22 of {_p} with ({_item} parsed as material) with lore "%{_bilgi}%" to nothing
	if ({_alis} parsed as integer) is not 0:
		if {_p}'s balance >= 640 * ({_alis} parsed as integer):
			set {_sonuc} to 640 * ({_alis} parsed as integer)
			make gui slot 27 of {_p} with stained glass:5 with lore "&a&l640 adet al!||&aFiyat: %{_sonuc}%" to run function alismarket({_p}, 640, "%{_item}%", "%{_sonuc}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
		else if {_p}'s balance < 640 * ({_alis} parsed as integer):
			make gui slot 27 of {_p} with stained glass:5 with lore "&c&l640 adet al!||&c%((640*({_alis} parsed as integer)) - {_p}'s balance)% oyun parası eksik." to nothing
		if {_p}'s balance >= 64 * ({_alis} parsed as integer):
			set {_sonuc} to 64 * ({_alis} parsed as integer)
			make gui slot 28 of {_p} with stained glass:5 with lore "&a&l64 adet al!||&aFiyat: %{_sonuc}%" to run function alismarket({_p}, 64, "%{_item}%", "%{_sonuc}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
		else if {_p}'s balance < 64 * ({_alis} parsed as integer):
			make gui slot 28 of {_p} with stained glass:5 with lore "&c&l64 adet al!||&c%((64*({_alis} parsed as integer)) - {_p}'s balance)% oyun parası eksik." to nothing
		if {_p}'s balance >= 10 * ({_alis} parsed as integer):
			set {_sonuc} to 10 * ({_alis} parsed as integer)
			make gui slot 29 of {_p} with stained glass:5 with lore "&a&l10 adet al!||&aFiyat: %{_sonuc}%" to run function alismarket({_p}, 10, "%{_item}%", "%{_sonuc}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
		else if {_p}'s balance < 10 * ({_alis} parsed as integer):
			make gui slot 29 of {_p} with stained glass:5 with lore "&c&l10 adet al!||&c%((10*({_alis} parsed as integer)) - {_p}'s balance)% oyun parası eksik." to nothing
		if {_p}'s balance >= 1 * ({_alis} parsed as integer):
			set {_sonuc} to 1 * ({_alis} parsed as integer)
			make gui slot 30 of {_p} with stained glass:5 with lore "&a&l1 adet al!||&aFiyat: %{_sonuc}%" to run function alismarket({_p}, 1, "%{_item}%", "%{_sonuc}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
		else if {_p}'s balance < 1 * ({_alis} parsed as integer):
			make gui slot 30 of {_p} with stained glass:5 with lore "&c&l1 adet al!||&c%((({_alis} parsed as integer)) - {_p}'s balance)% oyun parası eksik." to nothing
	if ({_satis} parsed as integer) is not 0:
		if number of ({_item} parsed as material) in {_p}'s inventory is bigger than or equal to 640:
			set {_sonuc} to 640 * ({_satis} parsed as integer)
			make gui slot 35 of {_p} with stained glass:5 with lore "&e&l640 adet sat!" to run function satismarket({_p}, 640, "%{_item}%", "%{_sonuc}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
		if number of ({_item} parsed as material) in {_p}'s inventory is smaller than 640:
			make gui slot 35 of {_p} with stained glass:5 with lore "&c&l640 adet sat!||&c%640 - (number of ({_item} parsed as material) in {_p}'s inventory)% eksik." to nothing
		if number of ({_item} parsed as material) in {_p}'s inventory is bigger than or equal to 64:
			set {_sonuc} to 64 * ({_satis} parsed as integer)
			make gui slot 34 of {_p} with stained glass:5 with lore "&e&l64 adet sat!" to run function satismarket({_p}, 64, "%{_item}%", "%{_sonuc}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
		if number of ({_item} parsed as material) in {_p}'s inventory is smaller than 64:
			make gui slot 34 of {_p} with stained glass:5 with lore "&c&l64 adet sat!||&c%64 - (number of ({_item} parsed as material) in {_p}'s inventory)% eksik." to nothing
		if number of ({_item} parsed as material) in {_p}'s inventory is bigger than or equal to 10:
			set {_sonuc} to 10 * ({_satis} parsed as integer)
			make gui slot 33 of {_p} with stained glass:5 with lore "&e&l10 adet sat!" to run function satismarket({_p}, 10, "%{_item}%", "%{_sonuc}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
		if number of ({_item} parsed as material) in {_p}'s inventory is smaller than 10:
			make gui slot 33 of {_p} with stained glass:5 with lore "&c&l10 adet sat!||&c%10 - (number of ({_item} parsed as material) in {_p}'s inventory)% eksik." to nothing
		if number of ({_item} parsed as material) in {_p}'s inventory is bigger than or equal to 1:
			set {_sonuc} to 1 * ({_satis} parsed as integer)
			make gui slot 32 of {_p} with stained glass:5 with lore "&e&l1 adet sat!" to run function satismarket({_p}, 1, "%{_item}%", "%{_sonuc}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
		if number of ({_item} parsed as material) in {_p}'s inventory is smaller than 1:
			make gui slot 32 of {_p} with stained glass:5 with lore "&c&l1 adet sat!||&c%1 - (number of ({_item} parsed as material) in {_p}'s inventory)% eksik." to nothing
function alismarket(p: player, sayi: integer, item: text, para: text, alis: text, satis: text, bilgi: text):
	if {_p} has enough space for {_sayi} of ({_item} parsed as material):
		remove ({_para} parsed as integer) from {_p}'s balance
		give {_sayi} of ({_item} parsed as material) to {_p}
		send "&6&lSanal Market &f&l» &3%{_sayi}% &aadet &e%{_item}% &d%{_para}% &aoyun parasıyla aldın." to {_p}
		onaymarket({_p}, "%{_item}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
	else:
		send "&6&lSanal Market &f&l» &cEnvanterinde yer kalmadı!" to {_p}
function satismarket(p: player, sayi: integer, item: text, para: text, alis: text, satis: text, bilgi: text):
	give ({_para} parsed as integer) to {_p}'s balance
	remove {_sayi} of ({_item} parsed as material) from {_p}
	send "&6&lSanal Market &f&l» &3%{_sayi}% &aadet &e%{_item}% &d%{_para}% &aoyun parasına sattın." to {_p}
	onaymarket({_p}, "%{_item}%", "%{_alis}%", "%{_satis}%", "%{_bilgi}%")
