on load:
	load yaml "plugins/SanalMarket/config.yml" as "marketSK"
command /market:
	trigger:
		MarketPage("1", player)
function MarketPage(page: text, p : player):
	set {_page} to "%{_page}%" parsed as integer
	open virtual chest with 6 row named "&0Market" to {_p}
	make gui slot 4 of {_p} with paper named "&f&oSayfa %{_page}%" to nothing
	set {_pagex::*} to page {_page} of (yaml nodes with keys "" of "marketSK") with 45 lines
	set {_geripage} to {_page} - 1
	set {_ileripage} to {_page} + 1
	set {_pageall} to size of (yaml nodes with keys "" of "marketSK")
	set {_pageall} to {_pageall} / 45
	set {_pageall} to ceil({_pageall})
	if {_geripage} > 0:
		make gui slot 0 of {_p} with (skull of "MHF_ARROWLEFT" parsed as offlineplayer) named "&c&oGeri sayfa" to run function MarketPage("%{_geripage}%", {_p})
	if {_ileripage} <= {_pageall}:
		make gui slot 8 of {_p} with (skull of "MHF_ARROWRIGHT" parsed as offlineplayer) named "&a&oİleri sayfa" to run function MarketPage("%{_ileripage}%", {_p})
	loop {_pagex::*}:
		set {_item} to loop-value parsed as material
		set {_list::*} to yaml value loop-value of "marketSK" split at ","
		set {_alis} to {_list::1}
		set {_satis} to {_list::2}
		make gui slot {_x} + 9 of {_p} with withLore({_item}, "", "&aAlış &f» &e%{_alis}%||&cSatış &f» &e%{_satis}%") to run function islem({_p}, "%{_alis}%", "%{_satis}%", "%{_item}%", {_page})
		add 1 to {_x}
function islem(p: player, alis: text, satis: text, item: text, page: integer):
	open virtual chest with 5 row named "Ne kadar?" to {_p}
	make gui slot integers between 0 and 44 of {_p} with ink sacwindowglass named " " to nothing
	set {_item} to "%{_item}%" parsed as material
	set {_alis} to "%{_alis}%" parsed as number
	set {_satis} to "%{_satis}%" parsed as number
	make gui slot 13 of {_p} with {_item} to nothing
	make gui slot 0 of {_p} with skull of "MHF_ARROWLEFT" parsed as offlineplayer named "&c&l← &cGeri" to run function MarketPage("%{_page}%", {_p})
	if {_alis} > 0:
		set {_.} to 0
		loop 18, 19, 20, 27, 28, 29, 36, 37 and 38:
			set {_adet} to 2^{_.}
			set {_-} to {_alis} * {_adet}
			if {_p}'s balance >= {_-}:
				make gui slot loop-number of {_p} with withLore(limewindowglass, "&a%{_adet}% adet satın al." , "&aAlış &f» %{_-}%") to run function MarketBuySell({_p}, "%{_adet}%", "%{_item}%", "%{_-}%", "-", {_page})
			else:
				make gui slot loop-number of {_p} with withLore(yellowwindowglass, "&cYetersiz bakiye.", "&6Gereken miktar &e» %{_-} - ({_p}'s balance)%")
			add 1 to {_.}
	if {_satis} > 0:
		set {_.} to 0
		loop 24, 25, 26, 33, 34, 35, 42, 43 and 44:
			set {_adet} to 2^{_.}
			if amount of {_item} in {_p}'s inventory >= {_adet}:
				set {_-} to {_satis} * {_adet}
				make gui slot loop-number of {_p} with withLore(redwindowglass, "&c%{_adet}% adet sat." , "&aSatış &f» %{_-}%") to run function MarketBuySell({_p}, "%{_adet}%", "%{_item}%", "%{_-}%", "+", {_page})
			else:
				make gui slot loop-number of {_p} with withLore(yellowwindowglass, "&cYetersiz ürün.", "&6Gereken ürün adeti &e» %{_adet} - (amount of {_item} in {_p}'s inventory)%")
			add 1 to {_.}
function MarketBuySell(p: player, adet: text, item: text, fiyat: text, pn: text, page: integer):
	set {_adet} to "%{_adet}%" parsed as integer
	set {_item} to "%{_item}%" parsed as material
	set {_fiyat} to "%{_fiyat}%" parsed as number
	if {_pn} is "-":
		remove {_fiyat} from {_p}'s balance
		if {_p} has enough space for {_adet} of {_item}:
			add {_adet} of {_item} to {_p}'s inventory
		else:
			drop {_adet} of {_item} at {_p}
		send "&aMarket &f» &eİşlem başarılı. Hesabından çekilen para miktarı &6%{_fiyat}%." to {_p}
	if {_pn} is "+":
		remove {_adet} of {_item} from {_p}
		add {_fiyat} to {_p}'s balance
		send "&aMarket &f» &eİşlem başarılı. Hesabına aktarılan para miktarı &6%{_fiyat}%." to {_p}
	set {_yaml} to yaml value "%{_item}%" of "marketSK"
	set {_list::*} to {_yaml} split at ","
	set {_1} to {_list::1}
	set {_2} to {_list::2}
	islem({_p}, "%{_1}%", "%{_2}%", "%{_item}%", {_page})
command /marketadmin [<text>] [<text>]:
	permission: op
	trigger:
		if arg-1 is "ekle":
			if arg-2 is set:
				set yaml value "%(type of tool of player)%" of "marketSK" to arg-2
				send "&aMarket&4Admin &f» &f&l[%type of tool of player%] → [%arg-2%]&e olarak ayarlandı."
				save yaml "marketSK"
				stop trigger
			else:
				send "&aMarket&4Admin &f» &cHatalı kullanım: &e/marketadmin (ekle/sil) <100,50>"
				stop trigger
		if arg-1 is "sil":
			if yaml value "%(type of tool of player)%" of "marketSK" does not exist:
				send "&aMarket&4Admin &f» &f&l[%type of tool of player%]&e markette bulunmamakta."
				stop trigger
			if yaml value "%(type of tool of player)%" of "marketSK" exists:
				delete yaml value "%(type of tool of player)%" of "marketSK"
				send "&aMarket&4Admin &f» &f&l[%type of tool of player%] &esilindi."
				save yaml "marketSK"
				stop trigger
		else:
			send "&aMarket&4Admin &f» &cHatalı kullanım: &e/marketadmin (ekle/sil) <100,50>"
			stop trigger
