options:
	prefix: &4[ &cParşömen &4]
	command: parsomen
	guiname: &0Yere düşürdüğün öğeler
	guibuyname: &0Parşömen Market
	satinal: &3Parşömen satın al.
	maliyet: 100
	sayi: 1 #Basılacak öğenin en fazla sayısı kaç olabilir? Birden fazla öğenin basılmasını istiyorsan 1'den fazla sayıyı ayarlayın. Fiziksel olarak en fazla sayı 64'tür.
	item: paper
	item-name: "&9Parşömen Kağıdı"
	item-lore: "", "&aKorunmasını istediğin öğenin", "&aüzerine bununla sağ tıkla." and ""
	satinalitem: paper
	satinalname: "&3Parşömen satın al."
	satinallore: "", "&7Satın almak için tıkla.", "", "&cMaliyet &f» &e100 oyun parası" and ""
	yetersizpara: &cYeteri kadar paran yok. Maliyet: 100 oyun parası
	parsomensatinalindi: &aBaşarıyla satın alındı.
	basilmisparsomenyazisi: "&7(*) &fKorumalı"
	ogelerdustu: &c&l(&4&l!&c&l) &f&lKorunmuş öğeler yere düştü. &e/parsomen gui&f&l'ye saklandı.
command /{@command} [<text>]:
	trigger:
		if arg-1 is "gui":
			open ParsomenGUI(player) to player
			stop trigger
		if arg-1 is "satınal", "buy" or "al":
			open ParsomenBuyGUI(player) to player
			stop trigger
		else:
			send ""
			send "&e/{@command} gui &7Kaybolan eşyalarını ara yüzünde listeler. Buradan geri çekebilirsiniz."
			send "&e/{@command} satınal&f|&ebuy&f|&eal &7Parşömen kağıdı buradan satın alınır."
			send ""
			send "&dSkript yapımcısı &5(bnjrKemal) &9Discord &7Maxwell##7329"
			send ""
function ParsomenGUI(p : player) :: inventory:
	set metadata tag "ParsomenGUI" of {_p} to chest inventory with 6 row with name "{@guiname}"
	loop {parsomen::%{_p}%::*}:
		set slot {_} + 0 of (metadata tag "ParsomenGUI" of {_p}) to loop-value
		add 1 to {_}
	set slot 53 of (metadata tag "ParsomenGUI" of {_p}) to hopper named "&aToplamak için tıkla!"
	return (metadata tag "ParsomenGUI" of {_p})
function ParsomenBuyGUI(p : player) :: inventory:
	set metadata tag "ParsomenBuyGUI" of {_p} to chest inventory with 3 row with name "{@guibuyname}"
	set slot (integers between 0 and 26) of (metadata tag "ParsomenBuyGUI" of {_p}) to black stained glass pane named " "
	set slot 13 of (metadata tag "ParsomenBuyGUI" of {_p}) to setNameLore({@satinalitem}, {@satinalname}, ({@satinallore}))
	return (metadata tag "ParsomenBuyGUI" of {_p})
on inventory click:
	if name of (player's current inventory) is "{@guiname}":
		cancel event
		index of event-slot = 53
		loop {parsomen::%player%::*}:
			player has space for loop-value
			remove loop-value from {parsomen::%player%::*}
			add loop-value to player's inventory
			remove loop-value from event-inventory
	if name of (player's current inventory) is "{@guibuyname}":
		cancel event
		index of event-slot = 13
		if player's balance >= {@maliyet}:
			remove {@maliyet} from player's balance
			give player setNameLore({@item}, {@item-name}, ({@item-lore}))
			send "{@prefix} {@parsomensatinalindi}"
		else if player's balance < {@maliyet}:
			send "{@prefix} {@yetersizpara}"
function setNameLore(item: material, name: text, lore: texts) :: material:
	set {_} to {_item}
	set name of {_} to {_name}
	delete lore of {_}
	loop {_lore::*}:
		add loop-value to lore of {_}
	return {_}
#---------
on inventory click:
	event-inventory = player's inventory
	#cancel event
	cursor slot of player is setNameLore({@item}, {@item-name}, ({@item-lore}))
	event-item is not air
	last element out of (lore of (event-slot)) is not {@basilmisparsomenyazisi}
	{@sayi} >= item amount of event-slot
	cancel event
	wait a tick
	remove 1 of cursor slot of player from cursor slot of player
	add {@basilmisparsomenyazisi} to lore of event-slot
on death of player:
	loop drops:
		if last element out of (lore of (loop-item)) is {@basilmisparsomenyazisi}:
			add loop-item to {parsomen::%victim%::*}
			remove loop-item from drops
		name of loop-item is {@item-name}
		add loop-item to {parsomen::%victim%::*}
		remove loop-item from drops
		set {_x} to true
	{_x} is true
	send "{@prefix} {@ogelerdustu}" to victim