variables:
	{guvenlik.kalan::%player%} = 0
options:
	guvenilir: "KingAdmin_YT"
on authme login:
	if player has permission "sk.güvenlik":
		if {guvenlik.ip::%player%} is IP of player:
			stop
		if {guvenlik.ip::%player%} is not IP of player:
			if {guvenlik.kalan::%player%} is bigger than or equal to 3:
				kick the player because "&c&lGüvenlik kodunu 3 kez yanlış girdiğin için sunucudan uzaklaştırıldın. Bizimle Discord'dan iletişime geçin. Kalan hakkın kalmadı."
				log "Güvenlik kodu giremeden uzaklaştırılan » %player% - %ip of player%" to "Skript\log_guvenlik.txt"
			else:
				set {guvenlik.dondur::%player%} to true
				loop 100 times:
					send ""
				send "&c&l&nGüvenlik kodu girin."
				wait 30 seconds
				if {guvenlik.dondur::%player%} is set:
					add 1 to {guvenlik.kalan::%player%}
					delete {guvenlik.dondur::%player%}
					kick the player because "&4&lGüvenlik kodu girmedin! Kalan hakkın: %{guvenlik.kalan::%player%}%/3"
					log "Güvenlik kodu giremeyen » %player% - %ip of player%" to "Skript\log_guvenlik.txt"
command /güvenlikx:
	permission: op
	trigger:
		if player is {@guvenilir}:
			if size of {guvenlik.kod::*} is smaller than or equal to 9:
				set {_y} to 1
			if size of {guvenlik.kod::*} is between 10 and 18:
				set {_y} to 2
			if size of {guvenlik.kod::*} is between 19 and 27:
				set {_y} to 3
			if size of {guvenlik.kod::*} is bigger than 27:
				set {_y} to 6
			open virtual chest with size {_y} named "&2Güvenli Hesaplar" to player
			set {_x} to 0
			loop {guvenlik.kod::*}:
				make gui slot {_x} of player with skull of (loop-index parsed as an offlineplayer) named "" with lore "&cİsim: &b%loop-index parsed as an offlineplayer%||&cKod: &b%loop-value%" to run function islem(player, loop-index)
				add 1 to {_x}
		else:
			send "&cBöyle bir komut bulunamadı."
			stop trigger
function islem(p: player, t: text):
	open virtual chest with size 3 named "&bAyarlar" to {_p}
	make gui slot 4 of {_p} with skull of ({_t} parsed as an offlineplayer) named "" with lore "&cİsim: &b%{_t}%||&cKOD: &b%{guvenlik.kod::%{_t}%}%" to nothing
	make gui slot 10 of {_p} with barrier named "&cBurdan çıkart." to run function islemx({_p}, "%{_t}%", "cikart")
	make gui slot 12 of {_p} with snowball named "&cKilidi kaldır." to run function islemx({_p}, "%{_t}%", "kaldir")
	make gui slot 14 of {_p} with emerald named "&cKod değiştir." to run function islemx({_p}, "%{_t}%", "koddegistir")
function islemx(p:player, t: text, z: text):
	if {_z} is "cikart":
		delete {guvenlik.kod::%{_t}%}
		close {_p}'s inventory
		send "&6Güvenlik listesinden &e%{_t}% adlı kişi &6çıkarıldı." to {_p}
	if {_z} is "kaldir":
		delete {guvenlik.kalan::%{_t}%}
		send "&e%{_t}% adlı kişinin &6hesabının kilidi açıldı." to {_p}
	if {_z} is "koddegistir":
		if {nochat.%{_p}%} is not set:
			set {nochat.%{_p}%} to true
			send "&a&l30 saniye içinde sohbet bölümüne KOD yaz!" to {_p}
			while {kod} is not set:
				if {kod} is set:
					set {guvenlik.kod::%{_t}%} to {kod}
					stop
			wait 30 seconds
			if {nochat.%{_p}%} is set:
				delete {nochat.%{_p}%}
				send "&c&lKOD sistemi iptal edildi." to {_p}
		set {guvenlik.kalan::%{_t}%} to 3
		send "&e%{_t}% adlı kişinin &6hesabının kodu %{kod}%." to {_p}
		delete {kod}
on chat:
	if {nochat.%player%} is set:
		cancel event
		send "&a&lBaşarıyla KOD kaydedildi."
		set {kod} to message
on quit:
	if {nochat.%player%} is set:
		delete {nochat.%player%}
