# skinofgui.sk (with SkinRestorer and TuSKe)
#	+{skinSKPlayer::%player%} !Already when loading, deleting... Never mind

# spawner.sk (with TuSKe)
#	+{spawnerDepo::%player%::*}
#	+{benzinSpawnerPlayer::%player%}

# drop.sk (with TuSKe)
# 	+{bagisdeposu::%player%::*}
# 	+{sneak::%player%} !Already when loading, deleting... Never mind

# arena.sk(with TuSKe)
# +{arena::X::*}, X = "gemi", "yay", "dovus", "magara" and "serbest"

# PURGE SYSTEM!

on load:
	loop {purge::*}:
		loop-value is smaller than now
		delete {benzinSpawnerPlayer::%loop-index%} and {spawnerDepo::%loop-index%::*} and {purge::%loop-index%} and {bagisdeposu::%loop-index%::*} and {arena::gemi::%loop-index%} and {arena::yay::%loop-index%} and {arena::dovus::%loop-index%} and {arena::magara::%loop-index%} and {arena::serbest::%loop-index%}
	delete {sneak::*} and {skinSKPlayer::*}
on quit:
	set {purge::%player%} to now
	add 3 month to {purge::%player%}

# PURGE SYSTEM!
