command /yetkililer [<text>] [<offlineplayer>] [<text>]:
	permission: op
	trigger:
		if arg-1 is "yardim":
			if arg-2 is not set:
				if arg-3 is not set:
					send "&6&l&m-----------------------------------------" to player
					send "" to player
					send "&f/yetkililer &6Yetkilileri gosterir."
					send "&f/yetkililer ekle <oyuncuadi> <grup> &6Yetkiliyi ekler."
					send "&f/yetkililer sil <oyuncuadi> &6Yetkiliyi siler."
					send "&f/yetkililer reset &6Tum yetkilileri temizler."
					send "" to player
					send "&6&l&m-----------------------------------------" to player
		else if arg-1 is "ekle":
			if arg-2 is set:
				if arg-3 is set:
					add offlineplayer-arg to {yetkililer::*}
					set {%arg-2%.yetki} to colored arg-3
					send "&a%arg-2% &6Adli oyuncu &abasariyla &c%colored arg-3% &6olarak eklendi."
		else if arg-1 is "sil":
			if arg-2 is set:
				remove offlineplayer-arg from {yetkililer::*}
				delete {%arg-2%.yetki}
				send "&a%arg-2% &cAdli oyuncu &abasariyla &csilindi!"
		else if arg-1 is "reset":
			if arg-2 is not set:
				if arg-3 is not set:
					loop {yetkililer::*}:
						delete {%loop-value%.yetki}
					wait 1 tick
					delete {yetkililer::*}
					send "&cTum yetkililer &abasariyla &csilindi!"
		else:
			send "&6&l&m-----------------------------------------" to player	
			send "" to player
			send "&f/yetkililer &6Yetkilileri gosterir."
			send "&f/yetkililer ekle <oyuncuadi> <grup> &6Yetkiliyi ekler."
			send "&f/yetkililer sil <oyuncuadi> &6Yetkiliyi siler."
			send "&f/yetkililer reset &6Tum yetkilileri temizler."
			send "" to player
			send "&6&l&m-----------------------------------------" to player
command /kadro:
	trigger:
		if size of {yetkililer::*} is between 0 and 9:
			wait 4 ticks
			set {_x} to -1
			open virtual chest with 1 rows named "&b&lEien&3&lMC &c&lEkipleri" to player
			loop {yetkililer::*}:
				add 1 to {_x}
				if loop-value is online:
					if loop-value is not afk:
						format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &a&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
					if loop-value is afk:
						format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &c&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
				else:
					format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &0&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
		else if size of {yetkililer::*} is between 10 and 18:
			wait 4 ticks
			set {_x} to -1
			open virtual chest with 2 rows named "&6&lYetkililer" to player
			loop {yetkililer::*}:
				add 1 to {_x}
				if loop-value is online:
					if loop-value is not afk:
						format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &a&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
					if loop-value is afk:
						format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &c&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
				else:
					format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &0&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
		else if size of {yetkililer::*} is between 18 and 27:
			wait 4 ticks
			set {_x} to -1
			open virtual chest with 3 rows named "&6&lYetkililer" to player
			loop {yetkililer::*}:
				add 1 to {_x}
				if loop-value is online:
					if loop-value is not afk:
						format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &a&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
					if loop-value is afk:
						format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &c&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
				else:
					format gui slot {_x} of player with loop-value's skull named "&b&l%loop-value%" with lore "%{%loop-value%.yetki}% &7&l| &0&l• &7&l| &f&lL.Q &e&l%last login of loop-value%" to close
		else if size of {yetkililer::*} is greater than 27:
			send "&cBu sunucuda gereginden fazla yetkili var. Lutfen &b/yetkililer reset &cyazarak hepsini silip tekrar ekleyin!" to player
		else:
			send "&cKadro bomboş!"
			stop trigger
