options:
	random: %random integer from 1 to 9%%random integer from 1 to 9%%random integer from 1 to 9%%random integer from 1 to 9%%random integer from 1 to 9%%random integer from 1 to 9%%random integer from 1 to 9%%random integer from 1 to 9%
every 30 minutes:
	number of all players is bigger than 5
	set {kelimeoyunu} to true
	set {kod} to "{@random}"
	send all players title "" with subtitle "&cÖdüllü oyun başlıyor!" for 2 seconds
	wait 2 seconds
	loop 200 times:
		send "" to all players
	send all players title "&cİlk yazan sen ol!" with subtitle "&b&l%{kod}%" for 999 seconds
	wait 10 seconds
	{kod} is set
	delete {kod}
	send all players title "" with subtitle "&cKimse kazanamadı!" for 3 seconds
on chat:
	{kelimeoyunu} is true
	message contains "%{kod}%"
	delete {kelimeoyunu}
	delete {kod}
	if {admindeneme} is not set:
		send all players title "" with subtitle "&b%player% &akazandı ve &a8 end taşı verildi!" for 3 seconds
		give 8 end stone to player
	else:
		send player title "" with subtitle "&b%player% &akazandı ve &a8 end taşı verildi!" for 3 seconds
		give 8 end stone to player
		delete {admindeneme}
command /kodeneme:
	permission: op
	trigger:
		send "sunucudaki oyuncu sayısı » %number of all players%"
		set {admindeneme} to true
		set {kelimeoyunu} to true
		set {kod} to "{@random}"
		send player title "" with subtitle "&cÖdüllü oyun başlıyor!" for 2 seconds
		wait 2 seconds
		send player title "&cİlk yazan sen ol!" with subtitle "&b&l%{kod}%" for 999 seconds
		wait 10 seconds
		{kod} is set
		delete {kod}
		send player title "" with subtitle "&cKimse kazanamadı!" for 3 seconds
